### ISSUE TITLE
\e[33mCleanup:\e[m Something went wrong!

### ISSUE THREAD

**Issue by L0y3r** [asdf-community/asdf-deno#26]
First of all thanks for this plugin

I'm using macOS big sur and when I try to install the latest version I get this error
```bash
∗ Downloading and installing deno...

\e[33mCleanup:\e[m Something went wrong!

21 /Users/marcoloyo/.asdf/plugins/deno/bin/install: curl --fail --silent --location --create-dirs --output "$source_path" "$download_url"
```

**Comment by yutakobayashidev** [comment]
same

**Comment by kealjones-wk** [comment]
This seems to be an issue caused by an inconsistency between the [Tags](https://github.com/denoland/deno/tags), which is what the versions list is created from, and the [Releases](https://github.com/denoland/deno/releases), which is where it is downloaded from. A Tag for version `1.17.2` could exist before a Release package is available which can cause this error since it cannot curl the download url since it does not exist.
